/*
Website System Name: DONORDOC-01 V1
Author: FRONTLENS LLC
License: For personal/business use only. Redistribution, resale, or sublicensing is strictly Copyright (c) 2026 FRONTLENS LLC. All rights reserved.
*/

export const setupPortalSchema = {
  websiteSystemId: "DONORDOC-01",
  schemaVersion: 1,
  destinationRules: {
    formats: {
      bareAnchor: "^#$",
      internalAnchor: "^#[A-Za-z][A-Za-z0-9_-]*$",
      absoluteWebUrl: "^https?:\\/\\/[A-Za-z0-9](?:[A-Za-z0-9-]*[A-Za-z0-9])?(?:\\.[A-Za-z0-9](?:[A-Za-z0-9-]*[A-Za-z0-9])?)*(?::\\d+)?(?:\\/[^\\s?#]*)?(?:\\?[^\\s#]*)?(?:#[^\\s]*)?$",
      relativePath: "^(?:\\/(?!\\/)\\S*|\\.\\.?\\/\\S*|(?![A-Za-z][A-Za-z0-9+.-]*:)(?![#/])\\S+)$",
      tel: "^tel:\\+?[0-9]+(?:[.\\- ][0-9]+| ?\\([0-9]+\\)(?:[.\\- ][0-9]+)*)*$",
    },
    linkDestination: {
      accept: ["bareAnchor", "internalAnchor", "absoluteWebUrl", "relativePath"],
      valid: ["#", "#about", "#pricing", "#consultation", "/privacy", "page.html", "https://example.com/", "https://example.com?x=1", "https://example.com#about", "http://example.com/path"],
      invalid: ["https://example..com/", "tel:+17866163592", "mailto:support@donordoc.com", "javascript:alert(1)"],
    },
    phoneDestination: {
      accept: ["tel"],
      valid: ["tel:+17866163592", "tel:17866163592", "tel:+1-786-616-3592"],
      invalid: ["tel:1---", "#footer", "https://example.com/", "(786) 616-3592"],
    },
    absoluteWebUrl: {
      accept: ["absoluteWebUrl"],
      valid: ["https://example.com/", "https://example.com?x=1", "https://example.com#about", "http://example.com/path"],
      invalid: ["https://example..com/", "#about", "#", "/privacy", "page.html", "tel:+17866163592", "example.com"],
    },
  },
  groups: [
    {
      id: "branding",
      label: "Branding",
      fields: [
        {
          id: "branding-logo-src",
          path: "branding.logo.src",
          label: "Logo",
          type: "image",
          permissions: { editable: true },
          required: true,
        },
        {
          id: "branding-logo-alt",
          path: "branding.logo.alt",
          label: "Logo Description",
          type: "text",
          permissions: { editable: true },
          required: false,
        },
        {
          id: "branding-favicon-src",
          path: "branding.favicon.src",
          label: "Favicon",
          type: "image",
          permissions: { editable: true },
          required: true,
        },
      ],
    },
    {
      id: "theme",
      label: "Theme",
      fields: [
        {
          id: "theme-variant",
          path: "theme.variant",
          label: "Website Color",
          type: "themeSelector",
          permissions: { editable: true },
          required: true,
          options: [
            { value: "trustGreen", label: "Trust Green" },
            { value: "professionalBlue", label: "Professional Blue" },
            { value: "executiveNavy", label: "Executive Navy" },
            { value: "healthcareTeal", label: "Healthcare Teal" },
          ],
        },
      ],
    },
    {
      id: "seo",
      label: "SEO & Social Sharing",
      fields: [
        {
          id: "seo-title",
          path: "seo.title",
          label: "Title",
          type: "text",
          permissions: { editable: true },
          required: true,
        },
        {
          id: "seo-description",
          path: "seo.description",
          label: "Description",
          type: "textarea",
          permissions: { editable: true },
          required: true,
        },
        {
          id: "seo-canonical-url",
          path: "seo.canonicalUrl",
          label: "Canonical URL",
          type: "url",
          permissions: { editable: true },
          destinationRule: "absoluteWebUrl",
          required: true,
        },
        {
          id: "seo-social-title",
          path: "seo.socialSharing.title",
          label: "Social Title",
          type: "text",
          permissions: { editable: true },
          required: true,
        },
        {
          id: "seo-social-description",
          path: "seo.socialSharing.description",
          label: "Social Description",
          type: "textarea",
          permissions: { editable: true },
          required: true,
        },
        {
          id: "seo-social-image",
          path: "seo.socialSharing.image",
          label: "Social Image",
          type: "image",
          permissions: { editable: true },
          required: true,
        },
        {
          id: "seo-social-url",
          path: "seo.socialSharing.url",
          label: "Social URL",
          type: "url",
          permissions: { editable: true },
          destinationRule: "absoluteWebUrl",
          required: true,
        },
      ],
    },
    {
      id: "navigation",
      label: "Navigation",
      fields: [
        {
          id: "navigation-items",
          path: "navigation.items",
          label: "Navigation Links",
          type: "collection",
          itemKey: "id",
          fields: [
            {
              id: "label",
              path: "label",
              label: "Link Label",
              type: "text",
              permissions: { editable: true },
              required: true,
            },
            {
              id: "href",
              path: "href",
              label: "Link Destination",
              type: "url",
              destinationRule: "linkDestination",
              required: true,
            },
          ],
        },
        {
          id: "navigation-primary-action-label",
          path: "navigation.primaryAction.label",
          label: "Primary Action Label",
          type: "text",
          permissions: { editable: true },
          required: true,
        },
        {
          id: "navigation-primary-action-href",
          path: "navigation.primaryAction.href",
          label: "Primary Action Destination",
          type: "url",
          destinationRule: "linkDestination",
          required: true,
        },
        {
          id: "navigation-secondary-action-label",
          path: "navigation.secondaryAction.label",
          label: "Secondary Action Label",
          type: "text",
          permissions: { editable: true },
          required: true,
        },
        {
          id: "navigation-secondary-action-href",
          path: "navigation.secondaryAction.href",
          label: "Secondary Action Destination",
          type: "url",
          destinationRule: "linkDestination",
          required: true,
        },
      ],
    },
    {
      id: "sections",
      label: "Sections",
      groups: [
        {
          id: "hero",
          label: "Hero",
          permissions: { replaceable: true },
          fields: [
            {
              id: "hero-enabled",
              path: "sections.hero.enabled",
              label: "Show Hero Section",
              type: "toggle",
              required: true,
            },
            {
              id: "hero-eyebrow",
              path: "sections.hero.eyebrow",
              label: "Eyebrow",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 39 },
            },
            {
              id: "hero-headline-main",
              path: "sections.hero.headline.main",
              label: "Headline",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 43 },
            },
            {
              id: "hero-headline-accent",
              path: "sections.hero.headline.accent",
              label: "Highlighted Headline",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 20 },
            },
            {
              id: "hero-description",
              path: "sections.hero.description",
              label: "Description",
              type: "textarea",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 119 },
            },
            {
              id: "hero-benefits",
              path: "sections.hero.benefits",
              label: "Benefits",
              type: "collection",
              fields: [
                {
                  id: "text",
                  path: "text",
                  label: "Benefit",
                  type: "text",
                  permissions: { editable: true },
                  required: true,
                  validation: { maxLength: 37 },
                },
              ],
            },
            {
              id: "hero-primary-cta-label",
              path: "sections.hero.primaryCta.label",
              label: "Primary Button Label",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 18 },
            },
            {
              id: "hero-primary-cta-href",
              path: "sections.hero.primaryCta.href",
              label: "Primary Button Destination",
              type: "url",
              permissions: { editable: true },
              destinationRule: "linkDestination",
              required: true,
            },
            {
              id: "hero-secondary-cta-label",
              path: "sections.hero.secondaryCta.label",
              label: "Secondary Button Label",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 23 },
            },
            {
              id: "hero-secondary-cta-href",
              path: "sections.hero.secondaryCta.href",
              label: "Secondary Button Destination",
              type: "url",
              permissions: { editable: true },
              destinationRule: "linkDestination",
              required: true,
            },
            {
              id: "hero-trust-line",
              path: "sections.hero.trustLine",
              label: "Trust Line",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 36 },
            },
            {
              id: "hero-image-mode",
              path: "sections.hero.image.mode",
              label: "Hero Image Source",
              type: "select",
              permissions: { editable: true },
              required: true,
              options: [
                { value: "theme", label: "Use Theme Image" },
                { value: "custom", label: "Use Custom Image" },
              ],
            },
            {
              id: "hero-custom-image",
              path: "sections.hero.image.customSrc",
              label: "Custom Hero Image",
              type: "image",
              permissions: { editable: true },
              required: false,
              condition: {
                path: "sections.hero.image.mode",
                equals: "custom",
              },
            },
            {
              id: "hero-image-alt",
              path: "sections.hero.image.alt",
              label: "Hero Image Description",
              type: "text",
              permissions: { editable: true },
              required: false,
              helpText:
                "Describe the custom image for accessibility when applicable.",
            },
            {
              id: "hero-floating-card-line-1",
              path: "sections.hero.floatingCard.line1",
              label: "Floating Card - Line 1",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 17 },
            },
            {
              id: "hero-floating-card-line-2",
              path: "sections.hero.floatingCard.line2",
              label: "Floating Card - Line 2",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 17 },
            },
            {
              id: "hero-floating-card-line-3",
              path: "sections.hero.floatingCard.line3",
              label: "Floating Card - Line 3",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 24 },
            },
          ],
        },
        {
          id: "trust",
          label: "Trust",
          permissions: { disableable: true },
          fields: [
            {
              id: "trust-enabled",
              path: "sections.trust.enabled",
              label: "Show Trust Section",
              type: "toggle",
              permissions: { editable: true },
              required: true,
            },
            {
              id: "trust-stats",
              path: "sections.trust.stats",
              label: "Stats",
              type: "collection",
              fields: [
                {
                  id: "value",
                  path: "value",
                  label: "Stat Value",
                  type: "text",
                  permissions: { editable: true },
                  required: true,
                },
                {
                  id: "label",
                  path: "label",
                  label: "Stat Label",
                  type: "text",
                  permissions: { editable: true },
                  required: true,
                  validation: { maxLength: 27 },
                },
              ],
            },
            {
              id: "trust-benefits",
              path: "sections.trust.benefits",
              label: "Benefits",
              type: "collection",
              fields: [
                {
                  id: "title",
                  path: "title",
                  label: "Benefit Title",
                  type: "text",
                  permissions: { editable: true },
                  required: true,
                  validation: { maxLength: 27 },
                },
                {
                  id: "description",
                  path: "description",
                  label: "Benefit Description",
                  type: "textarea",
                  permissions: { editable: true },
                  required: true,
                  validation: { maxLength: 54 },
                },
              ],
            },
          ],
        },
        {
          id: "about",
          label: "About",
          permissions: { disableable: true },
          fields: [
            {
              id: "about-enabled",
              path: "sections.about.enabled",
              label: "Show About Section",
              type: "toggle",
              permissions: { editable: true },
              required: true,
            },
            {
              id: "about-eyebrow",
              path: "sections.about.eyebrow",
              label: "Eyebrow",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 19 },
            },
            {
              id: "about-headline",
              path: "sections.about.headline",
              label: "Headline",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 36 },
            },
            {
              id: "about-description",
              path: "sections.about.description",
              label: "Description",
              type: "textarea",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 174 },
            },
            {
              id: "about-image-src",
              path: "sections.about.image.src",
              label: "Image",
              type: "image",
              permissions: { editable: true },
              required: true,
            },
            {
              id: "about-image-alt",
              path: "sections.about.image.alt",
              label: "Image Description",
              type: "text",
              permissions: { editable: true },
              required: false,
            },
          ],
        },
        {
          id: "services",
          label: "Services",
          permissions: { disableable: true },
          fields: [
            {
              id: "services-enabled",
              path: "sections.services.enabled",
              label: "Show Services Section",
              type: "toggle",
              permissions: { editable: true },
              required: true,
            },
            {
              id: "services-eyebrow",
              path: "sections.services.eyebrow",
              label: "Eyebrow",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 20 },
            },
            {
              id: "services-headline-main",
              path: "sections.services.headline.main",
              label: "Headline",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 30 },
            },
            {
              id: "services-headline-mid",
              path: "sections.services.headline.mid",
              label: "Headline Middle",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 9 },
            },
            {
              id: "services-headline-accent",
              path: "sections.services.headline.accent",
              label: "Highlighted Headline",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 19 },
            },
            {
              id: "services-description",
              path: "sections.services.description",
              label: "Description",
              type: "textarea",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 105 },
            },
            {
              id: "services-items",
              path: "sections.services.items",
              label: "Services",
              type: "collection",
              permissions: { reorderable: true },
              itemKey: "id",
              fields: [
                {
                  id: "title",
                  path: "title",
                  label: "Title",
                  type: "text",
                  permissions: { editable: true },
                  required: true,
                  validation: { maxLength: 27 },
                },
                {
                  id: "description",
                  path: "description",
                  label: "Description",
                  type: "textarea",
                  permissions: { editable: true },
                  required: true,
                  validation: { maxLength: 82 },
                },
              ],
            },
            {
              id: "services-cta-label",
              path: "sections.services.cta.label",
              label: "Button Label",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 29 },
            },
            {
              id: "services-cta-href",
              path: "sections.services.cta.href",
              label: "Button Destination",
              type: "url",
              permissions: { editable: true },
              destinationRule: "linkDestination",
              required: true,
            },
          ],
        },
        {
          id: "pricing",
          label: "Pricing",
          permissions: { disableable: true },
          fields: [
            {
              id: "pricing-enabled",
              path: "sections.pricing.enabled",
              label: "Show Pricing Section",
              type: "toggle",
              permissions: { editable: true },
              required: true,
            },
            {
              id: "pricing-eyebrow",
              path: "sections.pricing.eyebrow",
              label: "Eyebrow",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 31 },
            },
            {
              id: "pricing-headline-main",
              path: "sections.pricing.headline.main",
              label: "Headline",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 23 },
            },
            {
              id: "pricing-headline-accent",
              path: "sections.pricing.headline.accent",
              label: "Highlighted Headline",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 20 },
            },
            {
              id: "pricing-description",
              path: "sections.pricing.description",
              label: "Description",
              type: "textarea",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 101 },
            },
            {
              id: "pricing-plans",
              path: "sections.pricing.plans",
              label: "Plans",
              type: "collection",
              itemKey: "id",
              fields: [
                {
                  id: "name",
                  path: "name",
                  label: "Plan Name",
                  type: "text",
                  permissions: { editable: true },
                  required: true,
                  validation: { maxLength: 24 },
                },
                {
                  id: "badge",
                  path: "badge",
                  label: "Badge",
                  type: "text",
                  permissions: { editable: true },
                  required: false,
                  validation: { maxLength: 17 },
                },
                {
                  id: "description",
                  path: "description",
                  label: "Description",
                  type: "textarea",
                  permissions: { editable: true },
                  required: true,
                  validation: { maxLength: 76 },
                },
                {
                  id: "price-prefix",
                  path: "price.prefix",
                  label: "Price Prefix",
                  type: "text",
                  permissions: { editable: true },
                  required: true,
                },
                {
                  id: "price-amount",
                  path: "price.amount",
                  label: "Price",
                  type: "text",
                  permissions: { editable: true },
                  required: true,
                },
                {
                  id: "price-suffix",
                  path: "price.suffix",
                  label: "Price Suffix",
                  type: "text",
                  permissions: { editable: true },
                  required: true,
                },
                {
                  id: "features",
                  path: "features",
                  label: "Features",
                  type: "collection",
                  fields: [
                    {
                      id: "text",
                      path: "",
                      label: "Feature",
                      type: "text",
                      permissions: { editable: true },
                      required: true,
                      validation: { maxLength: 34 },
                    },
                  ],
                },
                {
                  id: "cta-label",
                  path: "cta.label",
                  label: "Button Label",
                  type: "text",
                  permissions: { editable: true },
                  required: true,
                  validation: { maxLength: 16 },
                },
                {
                  id: "cta-href",
                  path: "cta.href",
                  label: "Button Destination",
                  type: "url",
                  permissions: { editable: true },
                  destinationRule: "linkDestination",
                  required: true,
                },
              ],
            },
            {
              id: "pricing-advisor-headline",
              path: "sections.pricing.advisorCta.headline",
              label: "Advisor CTA Headline",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 41 },
            },
            {
              id: "pricing-advisor-description",
              path: "sections.pricing.advisorCta.description",
              label: "Advisor CTA Description",
              type: "textarea",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 76 },
            },
            {
              id: "pricing-advisor-label",
              path: "sections.pricing.advisorCta.button.label",
              label: "Advisor Button Label",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 23 },
            },
            {
              id: "pricing-advisor-href",
              path: "sections.pricing.advisorCta.button.href",
              label: "Advisor Button Destination",
              type: "url",
              permissions: { editable: true },
              destinationRule: "linkDestination",
              required: true,
            },
          ],
        },
        {
          id: "howItWorks",
          label: "How It Works",
          permissions: { disableable: true },
          fields: [
            {
              id: "how-it-works-enabled",
              path: "sections.howItWorks.enabled",
              label: "Show How It Works Section",
              type: "toggle",
              permissions: { editable: true },
              required: true,
            },
            {
              id: "how-it-works-eyebrow",
              path: "sections.howItWorks.eyebrow",
              label: "Eyebrow",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 17 },
            },
            {
              id: "how-it-works-headline-desktop-first",
              path: "sections.howItWorks.headline.desktop.first",
              label: "Headline, First Line",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 25 },
            },
            {
              id: "how-it-works-headline-desktop-second",
              path: "sections.howItWorks.headline.desktop.second",
              label: "Headline, Second Line",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 26 },
            },
            {
              id: "how-it-works-description",
              path: "sections.howItWorks.description",
              label: "Description",
              type: "textarea",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 150 },
            },
            {
              id: "how-it-works-groups",
              path: "sections.howItWorks.groups",
              label: "Groups",
              type: "collection",
              itemKey: "id",
              fields: [
                {
                  id: "label",
                  path: "label",
                  label: "Label",
                  type: "text",
                  permissions: { editable: true },
                  required: true,
                  validation: { maxLength: 14 },
                },
                {
                  id: "steps",
                  path: "steps",
                  label: "Steps",
                  type: "collection",
                  itemKey: "id",
                  fields: [
                    {
                      id: "number",
                      path: "number",
                      label: "Step Number",
                      type: "text",
                      permissions: { editable: true },
                      required: true,
                    },
                    {
                      id: "title",
                      path: "title",
                      label: "Title",
                      type: "text",
                      permissions: { editable: true },
                      required: true,
                      validation: { maxLength: 23 },
                    },
                    {
                      id: "description",
                      path: "description",
                      label: "Description",
                      type: "textarea",
                      permissions: { editable: true },
                      required: true,
                      validation: { maxLength: 88 },
                    },
                  ],
                },
              ],
            },
            {
              id: "how-it-works-summary",
              path: "sections.howItWorks.summary",
              label: "Summary",
              type: "collection",
              fields: [
                {
                  id: "text",
                  path: "text",
                  label: "Summary Text",
                  type: "text",
                  permissions: { editable: true },
                  required: true,
                  validation: { maxLength: 57 },
                },
              ],
            },
          ],
        },
        {
          id: "reviews",
          label: "Reviews",
          permissions: { disableable: true },
          fields: [
            {
              id: "reviews-enabled",
              path: "sections.reviews.enabled",
              label: "Show Reviews Section",
              type: "toggle",
              permissions: { editable: true },
              required: true,
            },
            {
              id: "reviews-headline-main",
              path: "sections.reviews.headline.main",
              label: "Headline",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 17 },
            },
            {
              id: "reviews-headline-accent",
              path: "sections.reviews.headline.accent",
              label: "Highlighted Headline",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 24 },
            },
            {
              id: "reviews-description",
              path: "sections.reviews.description",
              label: "Description",
              type: "textarea",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 104 },
            },
            {
              id: "reviews-items",
              path: "sections.reviews.items",
              label: "Reviews",
              type: "collection",
              itemKey: "id",
              fields: [
                {
                  id: "quote",
                  path: "quote",
                  label: "Quote",
                  type: "textarea",
                  permissions: { editable: true },
                  required: true,
                  validation: { maxLength: 148 },
                },
                {
                  id: "name",
                  path: "name",
                  label: "Name",
                  type: "text",
                  permissions: { editable: true },
                  required: true,
                  validation: { maxLength: 16 },
                },
                {
                  id: "clientType",
                  path: "clientType",
                  label: "Client Type",
                  type: "text",
                  permissions: { editable: true },
                  required: true,
                  validation: { maxLength: 31 },
                },
                {
                  id: "enrollmentText",
                  path: "enrollmentText",
                  label: "Enrollment Text",
                  type: "text",
                  permissions: { editable: true },
                  required: true,
                  validation: { maxLength: 21 },
                },
                {
                  id: "rating",
                  path: "rating",
                  label: "Rating",
                  type: "number",
                  permissions: { editable: true },
                  required: true,
                  validation: { minimum: 1, maximum: 5, integer: true },
                },
                {
                  id: "image-src",
                  path: "image.src",
                  label: "Photo",
                  type: "image",
                  permissions: { editable: true },
                  required: true,
                },
                {
                  id: "image-alt",
                  path: "image.alt",
                  label: "Photo Description",
                  type: "text",
                  permissions: { editable: true },
                  required: false,
                },
              ],
            },
          ],
        },
        {
          id: "faq",
          label: "FAQ",
          permissions: { disableable: true },
          fields: [
            {
              id: "faq-enabled",
              path: "sections.faq.enabled",
              label: "Show FAQ Section",
              type: "toggle",
              permissions: { editable: true },
              required: true,
            },
            {
              id: "faq-eyebrow",
              path: "sections.faq.eyebrow",
              label: "Eyebrow",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 15 },
            },
            {
              id: "faq-headline-before",
              path: "sections.faq.headline.before",
              label: "Headline Before",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 10 },
            },
            {
              id: "faq-headline-accent",
              path: "sections.faq.headline.accent",
              label: "Highlighted Headline",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 10 },
            },
            {
              id: "faq-headline-after",
              path: "sections.faq.headline.after",
              label: "Headline After",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 15 },
            },
            {
              id: "faq-description",
              path: "sections.faq.description",
              label: "Description",
              type: "textarea",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 103 },
            },
            {
              id: "faq-items",
              path: "sections.faq.items",
              label: "Questions",
              type: "collection",
              itemKey: "id",
              fields: [
                {
                  id: "question",
                  path: "question",
                  label: "Question",
                  type: "text",
                  permissions: { editable: true },
                  required: true,
                },
                {
                  id: "answer",
                  path: "answer",
                  label: "Answer",
                  type: "textarea",
                  permissions: { editable: true },
                  required: true,
                },
                {
                  id: "openByDefault",
                  path: "openByDefault",
                  label: "Open by Default",
                  type: "toggle",
                  permissions: { editable: true },
                  required: true,
                },
              ],
            },
            {
              id: "faq-cta-headline",
              path: "sections.faq.cta.headline",
              label: "CTA Headline",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 26 },
            },
            {
              id: "faq-cta-description",
              path: "sections.faq.cta.description",
              label: "CTA Description",
              type: "textarea",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 37 },
            },
            {
              id: "faq-cta-label",
              path: "sections.faq.cta.button.label",
              label: "Button Label",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 28 },
            },
            {
              id: "faq-cta-href",
              path: "sections.faq.cta.button.href",
              label: "Button Destination",
              type: "url",
              permissions: { editable: true },
              destinationRule: "linkDestination",
              required: true,
            },
          ],
        },
        {
          id: "consultation",
          label: "Consultation",
          permissions: { disableable: true },
          fields: [
            {
              id: "consultation-enabled",
              path: "sections.consultation.enabled",
              label: "Show Consultation Section",
              type: "toggle",
              permissions: { editable: true },
              required: true,
            },
            {
              id: "consultation-headline-main",
              path: "sections.consultation.headline.main",
              label: "Headline",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 26 },
            },
            {
              id: "consultation-headline-accent",
              path: "sections.consultation.headline.accent",
              label: "Highlighted Headline",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 22 },
            },
            {
              id: "consultation-description",
              path: "sections.consultation.description",
              label: "Description",
              type: "textarea",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 141 },
            },
            {
              id: "consultation-benefits",
              path: "sections.consultation.benefits",
              label: "Benefits",
              type: "collection",
              fields: [
                {
                  id: "title",
                  path: "title",
                  label: "Benefit Title",
                  type: "text",
                  permissions: { editable: true },
                  required: true,
                  validation: { maxLength: 26 },
                },
                {
                  id: "description",
                  path: "description",
                  label: "Benefit Description",
                  type: "textarea",
                  permissions: { editable: true },
                  required: true,
                  validation: { maxLength: 68 },
                },
              ],
            },
            {
              id: "consultation-image-src",
              path: "sections.consultation.image.src",
              label: "Image",
              type: "image",
              permissions: { editable: true },
              required: true,
            },
            {
              id: "consultation-image-alt",
              path: "sections.consultation.image.alt",
              label: "Image Description",
              type: "text",
              permissions: { editable: true },
              required: false,
            },
            {
              id: "consultation-form-title",
              path: "sections.consultation.form.title",
              label: "Form Title",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 42 },
            },
            {
              id: "consultation-form-subtitle",
              path: "sections.consultation.form.subtitle",
              label: "Form Subtitle",
              type: "textarea",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 57 },
            },
            {
              id: "consultation-preferred-date-label",
              path: "sections.consultation.form.fields.preferredDate.label",
              label: "Preferred Date Label",
              type: "text",
              permissions: { editable: true },
              required: true,
            },
            {
              id: "consultation-preferred-date-placeholder",
              path: "sections.consultation.form.fields.preferredDate.placeholder",
              label: "Preferred Date Placeholder",
              type: "text",
              permissions: { editable: true },
              required: true,
            },
            {
              id: "consultation-preferred-time-label",
              path: "sections.consultation.form.fields.preferredTime.label",
              label: "Preferred Time Label",
              type: "text",
              permissions: { editable: true },
              required: true,
            },
            {
              id: "consultation-preferred-time-placeholder",
              path: "sections.consultation.form.fields.preferredTime.placeholder",
              label: "Preferred Time Placeholder",
              type: "text",
              permissions: { editable: true },
              required: true,
            },
            {
              id: "consultation-coverage-label",
              path: "sections.consultation.form.fields.coverageType.label",
              label: "Coverage Type Label",
              type: "text",
              permissions: { editable: true },
              required: true,
            },
            {
              id: "consultation-coverage-placeholder",
              path: "sections.consultation.form.fields.coverageType.placeholder",
              label: "Coverage Type Placeholder",
              type: "text",
              permissions: { editable: true },
              required: true,
            },
            {
              id: "consultation-coverage-options",
              path: "sections.consultation.form.fields.coverageType.options",
              label: "Coverage Type Options",
              type: "collection",
              fields: [
                {
                  id: "option",
                  path: "",
                  label: "Option",
                  type: "text",
                  permissions: { editable: true },
                  required: true,
                },
              ],
            },
            {
              id: "consultation-contact-method-label",
              path: "sections.consultation.form.fields.contactMethod.label",
              label: "Contact Method Label",
              type: "text",
              permissions: { editable: true },
              required: true,
            },
            {
              id: "consultation-contact-method-placeholder",
              path: "sections.consultation.form.fields.contactMethod.placeholder",
              label: "Contact Method Placeholder",
              type: "text",
              permissions: { editable: true },
              required: true,
            },
            {
              id: "consultation-contact-method-options",
              path: "sections.consultation.form.fields.contactMethod.options",
              label: "Contact Method Options",
              type: "collection",
              fields: [
                {
                  id: "option",
                  path: "",
                  label: "Option",
                  type: "text",
                  permissions: { editable: true },
                  required: true,
                },
              ],
            },
            {
              id: "consultation-first-name-label",
              path: "sections.consultation.form.fields.firstName.label",
              label: "First Name Label",
              type: "text",
              permissions: { editable: true },
              required: true,
            },
            {
              id: "consultation-first-name-placeholder",
              path: "sections.consultation.form.fields.firstName.placeholder",
              label: "First Name Placeholder",
              type: "text",
              permissions: { editable: true },
              required: true,
            },
            {
              id: "consultation-last-name-label",
              path: "sections.consultation.form.fields.lastName.label",
              label: "Last Name Label",
              type: "text",
              permissions: { editable: true },
              required: true,
            },
            {
              id: "consultation-last-name-placeholder",
              path: "sections.consultation.form.fields.lastName.placeholder",
              label: "Last Name Placeholder",
              type: "text",
              permissions: { editable: true },
              required: true,
            },
            {
              id: "consultation-email-label",
              path: "sections.consultation.form.fields.email.label",
              label: "Email Label",
              type: "text",
              permissions: { editable: true },
              required: true,
            },
            {
              id: "consultation-email-placeholder",
              path: "sections.consultation.form.fields.email.placeholder",
              label: "Email Placeholder",
              type: "text",
              permissions: { editable: true },
              required: true,
            },
            {
              id: "consultation-phone-label",
              path: "sections.consultation.form.fields.phone.label",
              label: "Phone Label",
              type: "text",
              permissions: { editable: true },
              required: true,
            },
            {
              id: "consultation-phone-placeholder",
              path: "sections.consultation.form.fields.phone.placeholder",
              label: "Phone Placeholder",
              type: "text",
              permissions: { editable: true },
              required: true,
            },
            {
              id: "consultation-notes-label",
              path: "sections.consultation.form.fields.notes.label",
              label: "Notes Label",
              type: "text",
              permissions: { editable: true },
              required: true,
            },
            {
              id: "consultation-notes-placeholder",
              path: "sections.consultation.form.fields.notes.placeholder",
              label: "Notes Placeholder",
              type: "text",
              permissions: { editable: true },
              required: true,
            },
            {
              id: "consultation-submit-label",
              path: "sections.consultation.form.submitLabel",
              label: "Submit Button Label",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 26 },
            },
            {
              id: "consultation-secure-note",
              path: "sections.consultation.form.secureNote",
              label: "Secure Note",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 62 },
            },
          ],
        },
        {
          id: "finalCta",
          label: "Final CTA",
          fields: [
            {
              id: "final-cta-badge",
              path: "sections.finalCta.badge",
              label: "Badge",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 22 },
            },
            {
              id: "final-cta-headline-main",
              path: "sections.finalCta.headline.main",
              label: "Headline",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 27 },
            },
            {
              id: "final-cta-headline-accent",
              path: "sections.finalCta.headline.accent",
              label: "Highlighted Headline",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 21 },
            },
            {
              id: "final-cta-description",
              path: "sections.finalCta.description",
              label: "Description",
              type: "textarea",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 107 },
            },
            {
              id: "final-cta-image-src",
              path: "sections.finalCta.image.src",
              label: "Image",
              type: "image",
              permissions: { editable: true },
              required: true,
            },
            {
              id: "final-cta-image-alt",
              path: "sections.finalCta.image.alt",
              label: "Image Description",
              type: "text",
              permissions: { editable: true },
              required: false,
            },
            {
              id: "final-cta-label",
              path: "sections.finalCta.cta.label",
              label: "Button Label",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 28 },
            },
            {
              id: "final-cta-href",
              path: "sections.finalCta.cta.href",
              label: "Button Destination",
              type: "url",
              permissions: { editable: true },
              destinationRule: "linkDestination",
              required: true,
            },
            {
              id: "final-cta-secure-note",
              path: "sections.finalCta.secureNote",
              label: "Secure Note",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 62 },
            },
            {
              id: "final-cta-features",
              path: "sections.finalCta.features",
              label: "Features",
              type: "collection",
              fields: [
                {
                  id: "text",
                  path: "text",
                  label: "Feature",
                  type: "text",
                  permissions: { editable: true },
                  required: true,
                  validation: { maxLength: 26 },
                },
              ],
            },
          ],
        },
        {
          id: "footer",
          label: "Footer",
          fields: [
            {
              id: "footer-business-name",
              path: "sections.footer.businessName",
              label: "Business Name",
              type: "text",
              permissions: { editable: true },
              required: true,
            },
            {
              id: "footer-description",
              path: "sections.footer.description",
              label: "Brand Description",
              type: "textarea",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 99 },
            },
            {
              id: "footer-social-links",
              path: "sections.footer.socialLinks",
              label: "Social Links",
              type: "collection",
              itemKey: "id",
              fields: [
                {
                  id: "label",
                  path: "label",
                  label: "Link Label",
                  type: "text",
                  permissions: { editable: true },
                  required: true,
                },
                {
                  id: "href",
                  path: "href",
                  label: "Link Destination",
                  type: "url",
                  permissions: { editable: true },
                  destinationRule: "linkDestination",
                  required: true,
                },
              ],
            },
            {
              id: "footer-company-title",
              path: "sections.footer.linkGroups[id=company].title",
              label: "Company Column Title",
              type: "text",
              permissions: { editable: true },
              required: true,
            },
            {
              id: "footer-company-links",
              path: "sections.footer.linkGroups[id=company].links",
              label: "Company Links",
              type: "collection",
              itemKey: "id",
              fields: [
                {
                  id: "label",
                  path: "label",
                  label: "Link Label",
                  type: "text",
                  permissions: { editable: true },
                  required: true,
                  validation: { maxLength: 17 },
                },
                {
                  id: "href",
                  path: "href",
                  label: "Link Destination",
                  type: "url",
                  destinationRule: "linkDestination",
                  required: true,
                },
              ],
              itemRules: {
                contact: {
                  required: false,
                  permissions: { removable: true },
                  fields: {
                    href: { permissions: { editable: true } },
                  },
                },
              },
            },
            {
              id: "footer-coverage-title",
              path: "sections.footer.linkGroups[id=coverage].title",
              label: "Coverage Column Title",
              type: "text",
              permissions: { editable: true },
              required: true,
            },
            {
              id: "footer-coverage-links",
              path: "sections.footer.linkGroups[id=coverage].links",
              label: "Coverage Links",
              type: "collection",
              permissions: { removable: true },
              itemKey: "id",
              fields: [
                {
                  id: "label",
                  path: "label",
                  label: "Link Label",
                  type: "text",
                  permissions: { editable: true },
                  required: true,
                  validation: { maxLength: 24 },
                },
                {
                  id: "href",
                  path: "href",
                  label: "Link Destination",
                  type: "url",
                  permissions: { editable: true },
                  destinationRule: "linkDestination",
                  required: true,
                },
              ],
            },
            {
              id: "footer-resources-title",
              path: "sections.footer.linkGroups[id=resources].title",
              label: "Resources Column Title",
              type: "text",
              permissions: { editable: true },
              required: true,
            },
            {
              id: "footer-resources-links",
              path: "sections.footer.linkGroups[id=resources].links",
              label: "Resources Links",
              type: "collection",
              permissions: { removable: true },
              itemKey: "id",
              fields: [
                {
                  id: "label",
                  path: "label",
                  label: "Link Label",
                  type: "text",
                  permissions: { editable: true },
                  required: true,
                  validation: { maxLength: 28 },
                },
                {
                  id: "href",
                  path: "href",
                  label: "Link Destination",
                  type: "url",
                  permissions: { editable: true },
                  destinationRule: "linkDestination",
                  required: true,
                },
              ],
            },
            {
              id: "footer-phone-display",
              path: "sections.footer.contact.phone.display",
              label: "Phone",
              type: "text",
              permissions: { editable: true, removable: true },
              required: false,
              presence: {
                item: "sections.footer.contact.phone",
                absentWhen: ["omit", "null", "blankDisplay"],
                whenPresent: ["display", "href"],
              },
            },
            {
              id: "footer-phone-href",
              path: "sections.footer.contact.phone.href",
              label: "Phone Link",
              type: "url",
              permissions: { editable: true, removable: true },
              destinationRule: "phoneDestination",
              required: false,
              presence: {
                item: "sections.footer.contact.phone",
                absentWhen: ["omit", "null", "blankDisplay"],
                whenPresent: ["display", "href"],
              },
            },
            {
              id: "footer-email",
              path: "sections.footer.contact.email",
              label: "Email",
              type: "text",
              permissions: { editable: true, removable: true },
              required: false,
              presence: {
                item: "sections.footer.contact.email",
                absentWhen: ["omit", "null", "blank"],
              },
            },
            {
              id: "footer-address",
              path: "sections.footer.contact.address",
              label: "Address",
              type: "text",
              permissions: { editable: true, removable: true },
              required: false,
              presence: {
                item: "sections.footer.contact.address",
                absentWhen: ["omit", "null", "blank"],
              },
            },
            {
              id: "footer-hours",
              path: "sections.footer.contact.hours",
              label: "Hours",
              type: "text",
              permissions: { editable: true, removable: true },
              required: false,
              validation: { maxLength: 42 },
              presence: {
                item: "sections.footer.contact.hours",
                absentWhen: ["omit", "null", "blank"],
              },
            },
            {
              id: "footer-secure-note",
              path: "sections.footer.secureNote",
              label: "Secure Note",
              type: "text",
              permissions: { editable: true },
              required: true,
              validation: { maxLength: 62 },
            },
            {
              id: "footer-copyright-text",
              path: "sections.footer.copyrightText",
              label: "Copyright Text",
              type: "text",
              permissions: { editable: true },
              required: true,
            },
            {
              id: "footer-legal-links",
              path: "sections.footer.legalLinks",
              label: "Legal Links",
              type: "collection",
              itemKey: "id",
              fields: [
                {
                  id: "label",
                  path: "label",
                  label: "Link Label",
                  type: "text",
                  required: true,
                },
                {
                  id: "href",
                  path: "href",
                  label: "Link Destination",
                  type: "url",
                  permissions: { editable: true },
                  destinationRule: "linkDestination",
                  required: true,
                },
              ],
              itemRules: {
                privacy: { required: true },
                terms: { required: true },
                siteMap: {
                  required: false,
                  permissions: { removable: true },
                  fields: {
                    label: {
                      permissions: { editable: true },
                      validation: { maxLength: 13 },
                    },
                  },
                },
              },
            },
          ],
        },
      ],
    },
  ],
};
